apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pipeline-pvc
  namespace: linuxman11-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
