apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  WP_DEBUG: {{ .Values.wordpress.config.debug | quote }}
  WP_MEMORY_LIMIT: {{ .Values.wordpress.config.memoryLimit | quote }}
  WP_MAX_UPLOAD_SIZE: {{ .Values.wordpress.config.maxUploadSize | quote }}
