apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Release.Name }}-role
